/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 30
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__simple_ident = 1,
  anon_sym_Puzzles = 2,
  anon_sym_COLON = 3,
  aux_sym_puzzle_definition_token1 = 4,
  anon_sym_PIPE = 5,
  anon_sym_solved_DASHgoto = 6,
  anon_sym_input = 7,
  anon_sym_max_DASHinput = 8,
  sym__number = 9,
  sym_string = 10,
  sym_source_file = 11,
  sym__puzzle_definition_section = 12,
  sym_puzzle_definition = 13,
  aux_sym__instructions = 14,
  sym_instruction = 15,
  sym_solved_goto_instruction = 16,
  sym_input_instruction = 17,
  aux_sym__positions = 18,
  sym__position = 19,
  sym_algorithm = 20,
  sym_move = 21,
  aux_sym__puzzle_definition_section_repeat1 = 22,
  aux_sym_algorithm_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__simple_ident] = "_simple_ident",
  [anon_sym_Puzzles] = "Puzzles",
  [anon_sym_COLON] = ":",
  [aux_sym_puzzle_definition_token1] = "puzzle_definition_token1",
  [anon_sym_PIPE] = "|",
  [anon_sym_solved_DASHgoto] = "solved-goto",
  [anon_sym_input] = "input",
  [anon_sym_max_DASHinput] = "max-input",
  [sym__number] = "_number",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym__puzzle_definition_section] = "_puzzle_definition_section",
  [sym_puzzle_definition] = "puzzle_definition",
  [aux_sym__instructions] = "_instructions",
  [sym_instruction] = "instruction",
  [sym_solved_goto_instruction] = "solved_goto_instruction",
  [sym_input_instruction] = "input_instruction",
  [aux_sym__positions] = "_positions",
  [sym__position] = "_position",
  [sym_algorithm] = "algorithm",
  [sym_move] = "move",
  [aux_sym__puzzle_definition_section_repeat1] = "_puzzle_definition_section_repeat1",
  [aux_sym_algorithm_repeat1] = "algorithm_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__simple_ident] = sym__simple_ident,
  [anon_sym_Puzzles] = anon_sym_Puzzles,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_puzzle_definition_token1] = aux_sym_puzzle_definition_token1,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_solved_DASHgoto] = anon_sym_solved_DASHgoto,
  [anon_sym_input] = anon_sym_input,
  [anon_sym_max_DASHinput] = anon_sym_max_DASHinput,
  [sym__number] = sym__number,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym__puzzle_definition_section] = sym__puzzle_definition_section,
  [sym_puzzle_definition] = sym_puzzle_definition,
  [aux_sym__instructions] = aux_sym__instructions,
  [sym_instruction] = sym_instruction,
  [sym_solved_goto_instruction] = sym_solved_goto_instruction,
  [sym_input_instruction] = sym_input_instruction,
  [aux_sym__positions] = aux_sym__positions,
  [sym__position] = sym__position,
  [sym_algorithm] = sym_algorithm,
  [sym_move] = sym_move,
  [aux_sym__puzzle_definition_section_repeat1] = aux_sym__puzzle_definition_section_repeat1,
  [aux_sym_algorithm_repeat1] = aux_sym_algorithm_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__simple_ident] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_Puzzles] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_puzzle_definition_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_solved_DASHgoto] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_input] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_max_DASHinput] = {
    .visible = true,
    .named = false,
  },
  [sym__number] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__puzzle_definition_section] = {
    .visible = false,
    .named = true,
  },
  [sym_puzzle_definition] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__instructions] = {
    .visible = false,
    .named = false,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_solved_goto_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_input_instruction] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__positions] = {
    .visible = false,
    .named = false,
  },
  [sym__position] = {
    .visible = false,
    .named = true,
  },
  [sym_algorithm] = {
    .visible = true,
    .named = true,
  },
  [sym_move] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__puzzle_definition_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_algorithm_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_algorithm = 1,
  field_index = 2,
  field_max_input = 3,
  field_message = 4,
  field_name = 5,
  field_positions = 6,
  field_target = 7,
  field_type = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_algorithm] = "algorithm",
  [field_index] = "index",
  [field_max_input] = "max_input",
  [field_message] = "message",
  [field_name] = "name",
  [field_positions] = "positions",
  [field_target] = "target",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_type, 2},
  [2] =
    {field_index, 0},
  [3] =
    {field_positions, 1},
    {field_target, 2},
  [5] =
    {field_algorithm, 2},
    {field_max_input, 4},
    {field_message, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 4,
  [13] = 3,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 17,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
};

static const TSCharacterRange sym__simple_ident_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'#', '#'}, {'%', '\''}, {'*', '+'}, {'/', '9'}, {';', ';'}, {'=', 'z'},
  {'|', '|'}, {'~', 0x218f}, {0x2191, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'm') ADVANCE(29);
      if (lookahead == 's') ADVANCE(33);
      if (lookahead == '|') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(36);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(26);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 3:
      if (lookahead == 'g') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'i') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == 'm') ADVANCE(29);
      if (lookahead == 's') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(36);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'p') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(7);
      END_STATE();
    case 12:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 13:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 14:
      if (eof) ADVANCE(16);
      if (lookahead == '|') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(36);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_puzzle_definition_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(36);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_solved_DASHgoto);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_max_DASHinput);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym__number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(36);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym__number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == '-') ADVANCE(4);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(36);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == '-') ADVANCE(3);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(36);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == 'a') ADVANCE(35);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(36);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == 'd') ADVANCE(28);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(36);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == 'e') ADVANCE(30);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(36);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == 'l') ADVANCE(34);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(36);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == 'o') ADVANCE(32);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(36);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == 'v') ADVANCE(31);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == 'x') ADVANCE(27);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__simple_ident);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(36);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'P') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'u') ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == 'z') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == 'p') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == 'z') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_input);
      END_STATE();
    case 11:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_Puzzles);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 5},
  [3] = {.lex_state = 15},
  [4] = {.lex_state = 15},
  [5] = {.lex_state = 15},
  [6] = {.lex_state = 14},
  [7] = {.lex_state = 15},
  [8] = {.lex_state = 14},
  [9] = {.lex_state = 15},
  [10] = {.lex_state = 15},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 14},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 15},
  [18] = {.lex_state = 15},
  [19] = {.lex_state = 14},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 14},
  [22] = {.lex_state = 14},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 13},
  [25] = {.lex_state = 14},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 14},
  [29] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__simple_ident] = ACTIONS(1),
    [anon_sym_Puzzles] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_solved_DASHgoto] = ACTIONS(1),
    [anon_sym_input] = ACTIONS(1),
    [anon_sym_max_DASHinput] = ACTIONS(1),
    [sym__number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(23),
    [sym__puzzle_definition_section] = STATE(15),
    [anon_sym_Puzzles] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      sym__simple_ident,
    ACTIONS(7), 1,
      anon_sym_solved_DASHgoto,
    ACTIONS(9), 1,
      anon_sym_input,
    STATE(4), 2,
      sym_move,
      aux_sym_algorithm_repeat1,
    STATE(19), 3,
      sym_solved_goto_instruction,
      sym_input_instruction,
      sym_algorithm,
  [19] = 4,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      sym__simple_ident,
    ACTIONS(16), 1,
      sym__number,
    STATE(3), 2,
      sym_move,
      aux_sym_algorithm_repeat1,
  [33] = 4,
    ACTIONS(5), 1,
      sym__simple_ident,
    ACTIONS(18), 1,
      ts_builtin_sym_end,
    ACTIONS(20), 1,
      sym__number,
    STATE(3), 2,
      sym_move,
      aux_sym_algorithm_repeat1,
  [47] = 3,
    ACTIONS(22), 1,
      sym__simple_ident,
    ACTIONS(24), 1,
      sym__number,
    STATE(7), 2,
      sym_puzzle_definition,
      aux_sym__puzzle_definition_section_repeat1,
  [58] = 3,
    ACTIONS(26), 1,
      ts_builtin_sym_end,
    ACTIONS(28), 1,
      sym__number,
    STATE(8), 2,
      aux_sym__instructions,
      sym_instruction,
  [69] = 3,
    ACTIONS(30), 1,
      sym__simple_ident,
    ACTIONS(33), 1,
      sym__number,
    STATE(7), 2,
      sym_puzzle_definition,
      aux_sym__puzzle_definition_section_repeat1,
  [80] = 3,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      sym__number,
    STATE(8), 2,
      aux_sym__instructions,
      sym_instruction,
  [91] = 3,
    ACTIONS(40), 1,
      sym__simple_ident,
    ACTIONS(42), 1,
      sym__number,
    STATE(10), 2,
      aux_sym__positions,
      sym__position,
  [102] = 3,
    ACTIONS(44), 1,
      sym__simple_ident,
    ACTIONS(47), 1,
      sym__number,
    STATE(10), 2,
      aux_sym__positions,
      sym__position,
  [113] = 3,
    ACTIONS(49), 1,
      sym__simple_ident,
    STATE(27), 1,
      sym_algorithm,
    STATE(12), 2,
      sym_move,
      aux_sym_algorithm_repeat1,
  [124] = 3,
    ACTIONS(18), 1,
      anon_sym_max_DASHinput,
    ACTIONS(51), 1,
      sym__simple_ident,
    STATE(13), 2,
      sym_move,
      aux_sym_algorithm_repeat1,
  [135] = 3,
    ACTIONS(11), 1,
      anon_sym_max_DASHinput,
    ACTIONS(53), 1,
      sym__simple_ident,
    STATE(13), 2,
      sym_move,
      aux_sym_algorithm_repeat1,
  [146] = 2,
    ACTIONS(56), 1,
      sym__simple_ident,
    STATE(5), 2,
      sym_puzzle_definition,
      aux_sym__puzzle_definition_section_repeat1,
  [154] = 2,
    ACTIONS(28), 1,
      sym__number,
    STATE(6), 2,
      aux_sym__instructions,
      sym_instruction,
  [162] = 2,
    ACTIONS(58), 1,
      sym__simple_ident,
    STATE(9), 2,
      aux_sym__positions,
      sym__position,
  [170] = 2,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 2,
      sym__number,
      sym__simple_ident,
  [178] = 1,
    ACTIONS(64), 2,
      sym__number,
      sym__simple_ident,
  [183] = 1,
    ACTIONS(66), 2,
      ts_builtin_sym_end,
      sym__number,
  [188] = 2,
    ACTIONS(60), 1,
      anon_sym_max_DASHinput,
    ACTIONS(62), 1,
      sym__simple_ident,
  [195] = 1,
    ACTIONS(68), 2,
      ts_builtin_sym_end,
      sym__number,
  [200] = 1,
    ACTIONS(70), 2,
      ts_builtin_sym_end,
      sym__number,
  [205] = 1,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
  [209] = 1,
    ACTIONS(74), 1,
      aux_sym_puzzle_definition_token1,
  [213] = 1,
    ACTIONS(76), 1,
      anon_sym_PIPE,
  [217] = 1,
    ACTIONS(78), 1,
      anon_sym_COLON,
  [221] = 1,
    ACTIONS(80), 1,
      anon_sym_max_DASHinput,
  [225] = 1,
    ACTIONS(82), 1,
      sym__number,
  [229] = 1,
    ACTIONS(84), 1,
      sym_string,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 19,
  [SMALL_STATE(4)] = 33,
  [SMALL_STATE(5)] = 47,
  [SMALL_STATE(6)] = 58,
  [SMALL_STATE(7)] = 69,
  [SMALL_STATE(8)] = 80,
  [SMALL_STATE(9)] = 91,
  [SMALL_STATE(10)] = 102,
  [SMALL_STATE(11)] = 113,
  [SMALL_STATE(12)] = 124,
  [SMALL_STATE(13)] = 135,
  [SMALL_STATE(14)] = 146,
  [SMALL_STATE(15)] = 154,
  [SMALL_STATE(16)] = 162,
  [SMALL_STATE(17)] = 170,
  [SMALL_STATE(18)] = 178,
  [SMALL_STATE(19)] = 183,
  [SMALL_STATE(20)] = 188,
  [SMALL_STATE(21)] = 195,
  [SMALL_STATE(22)] = 200,
  [SMALL_STATE(23)] = 205,
  [SMALL_STATE(24)] = 209,
  [SMALL_STATE(25)] = 213,
  [SMALL_STATE(26)] = 217,
  [SMALL_STATE(27)] = 221,
  [SMALL_STATE(28)] = 225,
  [SMALL_STATE(29)] = 229,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_algorithm_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_algorithm_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [16] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_algorithm_repeat1, 2, 0, 0),
  [18] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_algorithm, 1, 0, 0),
  [20] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_algorithm, 1, 0, 0),
  [22] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [24] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__puzzle_definition_section, 2, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__puzzle_definition_section_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__puzzle_definition_section_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__instructions, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__instructions, 2, 0, 0), SHIFT_REPEAT(25),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__positions, 2, 0, 0), SHIFT_REPEAT(10),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__positions, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_algorithm_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_move, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_move, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_puzzle_definition, 3, 0, 1),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 3, 0, 2),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solved_goto_instruction, 3, 0, 3),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input_instruction, 5, 0, 4),
  [72] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_qter_q(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym__simple_ident,
    .primary_state_ids = ts_primary_state_ids,
    .name = "qter_q",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
