/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 61
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 40
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__simple_ident = 1,
  anon_sym_Puzzles = 2,
  anon_sym_COLON = 3,
  anon_sym_PIPE = 4,
  anon_sym_goto = 5,
  anon_sym_solved_DASHgoto = 6,
  sym_solve_instruction = 7,
  anon_sym_repeat = 8,
  anon_sym_until = 9,
  anon_sym_solved = 10,
  anon_sym_input = 11,
  anon_sym_max_DASHinput = 12,
  anon_sym_halt = 13,
  anon_sym_print = 14,
  anon_sym_counting_DASHuntil = 15,
  anon_sym_switch = 16,
  sym__number = 17,
  sym_string = 18,
  sym_source_file = 19,
  sym__puzzle_definition_section = 20,
  sym_puzzle_definition = 21,
  aux_sym__instructions = 22,
  sym_instruction = 23,
  sym_goto_instruction = 24,
  sym_solved_goto_instruction = 25,
  sym_repeat_until_instruction = 26,
  sym_input_instruction = 27,
  sym_halt_instruction = 28,
  sym_print_instruction = 29,
  sym_switch_instruction = 30,
  sym_positions = 31,
  sym_position = 32,
  sym_algorithm = 33,
  sym_move = 34,
  sym_puzzle_name = 35,
  sym_puzzle_type = 36,
  aux_sym__puzzle_definition_section_repeat1 = 37,
  aux_sym_positions_repeat1 = 38,
  aux_sym_algorithm_repeat1 = 39,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__simple_ident] = "_simple_ident",
  [anon_sym_Puzzles] = "Puzzles",
  [anon_sym_COLON] = ":",
  [anon_sym_PIPE] = "|",
  [anon_sym_goto] = "goto",
  [anon_sym_solved_DASHgoto] = "solved-goto",
  [sym_solve_instruction] = "solve_instruction",
  [anon_sym_repeat] = "repeat",
  [anon_sym_until] = "until",
  [anon_sym_solved] = "solved",
  [anon_sym_input] = "input",
  [anon_sym_max_DASHinput] = "max-input",
  [anon_sym_halt] = "halt",
  [anon_sym_print] = "print",
  [anon_sym_counting_DASHuntil] = "counting-until",
  [anon_sym_switch] = "switch",
  [sym__number] = "_number",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym__puzzle_definition_section] = "_puzzle_definition_section",
  [sym_puzzle_definition] = "puzzle_definition",
  [aux_sym__instructions] = "_instructions",
  [sym_instruction] = "instruction",
  [sym_goto_instruction] = "goto_instruction",
  [sym_solved_goto_instruction] = "solved_goto_instruction",
  [sym_repeat_until_instruction] = "repeat_until_instruction",
  [sym_input_instruction] = "input_instruction",
  [sym_halt_instruction] = "halt_instruction",
  [sym_print_instruction] = "print_instruction",
  [sym_switch_instruction] = "switch_instruction",
  [sym_positions] = "positions",
  [sym_position] = "position",
  [sym_algorithm] = "algorithm",
  [sym_move] = "move",
  [sym_puzzle_name] = "puzzle_name",
  [sym_puzzle_type] = "puzzle_type",
  [aux_sym__puzzle_definition_section_repeat1] = "_puzzle_definition_section_repeat1",
  [aux_sym_positions_repeat1] = "positions_repeat1",
  [aux_sym_algorithm_repeat1] = "algorithm_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__simple_ident] = sym__simple_ident,
  [anon_sym_Puzzles] = anon_sym_Puzzles,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_goto] = anon_sym_goto,
  [anon_sym_solved_DASHgoto] = anon_sym_solved_DASHgoto,
  [sym_solve_instruction] = sym_solve_instruction,
  [anon_sym_repeat] = anon_sym_repeat,
  [anon_sym_until] = anon_sym_until,
  [anon_sym_solved] = anon_sym_solved,
  [anon_sym_input] = anon_sym_input,
  [anon_sym_max_DASHinput] = anon_sym_max_DASHinput,
  [anon_sym_halt] = anon_sym_halt,
  [anon_sym_print] = anon_sym_print,
  [anon_sym_counting_DASHuntil] = anon_sym_counting_DASHuntil,
  [anon_sym_switch] = anon_sym_switch,
  [sym__number] = sym__number,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym__puzzle_definition_section] = sym__puzzle_definition_section,
  [sym_puzzle_definition] = sym_puzzle_definition,
  [aux_sym__instructions] = aux_sym__instructions,
  [sym_instruction] = sym_instruction,
  [sym_goto_instruction] = sym_goto_instruction,
  [sym_solved_goto_instruction] = sym_solved_goto_instruction,
  [sym_repeat_until_instruction] = sym_repeat_until_instruction,
  [sym_input_instruction] = sym_input_instruction,
  [sym_halt_instruction] = sym_halt_instruction,
  [sym_print_instruction] = sym_print_instruction,
  [sym_switch_instruction] = sym_switch_instruction,
  [sym_positions] = sym_positions,
  [sym_position] = sym_position,
  [sym_algorithm] = sym_algorithm,
  [sym_move] = sym_move,
  [sym_puzzle_name] = sym_puzzle_name,
  [sym_puzzle_type] = sym_puzzle_type,
  [aux_sym__puzzle_definition_section_repeat1] = aux_sym__puzzle_definition_section_repeat1,
  [aux_sym_positions_repeat1] = aux_sym_positions_repeat1,
  [aux_sym_algorithm_repeat1] = aux_sym_algorithm_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__simple_ident] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_Puzzles] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_goto] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_solved_DASHgoto] = {
    .visible = true,
    .named = false,
  },
  [sym_solve_instruction] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_repeat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_until] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_solved] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_input] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_max_DASHinput] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_halt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_print] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_counting_DASHuntil] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_switch] = {
    .visible = true,
    .named = false,
  },
  [sym__number] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__puzzle_definition_section] = {
    .visible = false,
    .named = true,
  },
  [sym_puzzle_definition] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__instructions] = {
    .visible = false,
    .named = false,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_goto_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_solved_goto_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_repeat_until_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_input_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_halt_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_print_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_switch_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_positions] = {
    .visible = true,
    .named = true,
  },
  [sym_position] = {
    .visible = true,
    .named = true,
  },
  [sym_algorithm] = {
    .visible = true,
    .named = true,
  },
  [sym_move] = {
    .visible = true,
    .named = true,
  },
  [sym_puzzle_name] = {
    .visible = true,
    .named = true,
  },
  [sym_puzzle_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__puzzle_definition_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_positions_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_algorithm_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_algorithm = 1,
  field_index = 2,
  field_max_input = 3,
  field_message = 4,
  field_name = 5,
  field_positions = 6,
  field_target = 7,
  field_type = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_algorithm] = "algorithm",
  [field_index] = "index",
  [field_max_input] = "max_input",
  [field_message] = "message",
  [field_name] = "name",
  [field_positions] = "positions",
  [field_target] = "target",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 3},
  [8] = {.index = 12, .length = 3},
  [9] = {.index = 15, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_type, 2},
  [2] =
    {field_index, 0},
  [3] =
    {field_target, 1},
  [4] =
    {field_message, 1},
  [5] =
    {field_positions, 1},
    {field_target, 2},
  [7] =
    {field_algorithm, 4},
    {field_positions, 2},
  [9] =
    {field_algorithm, 2},
    {field_max_input, 4},
    {field_message, 1},
  [12] =
    {field_algorithm, 2},
    {field_message, 1},
    {field_positions, 4},
  [15] =
    {field_algorithm, 5},
    {field_message, 4},
    {field_positions, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 4,
  [9] = 6,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 11,
  [14] = 14,
  [15] = 10,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 11,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 10,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 27,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 30,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 30,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
};

static const TSCharacterRange sym__simple_ident_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'#', '#'}, {'%', '\''}, {'*', '+'}, {'/', '9'}, {';', ';'}, {'=', 'z'},
  {'|', '|'}, {'~', 0x218f}, {0x2191, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == 'c') ADVANCE(42);
      if (lookahead == 'm') ADVANCE(34);
      if (lookahead == 's') ADVANCE(43);
      if (lookahead == '|') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == 'c') ADVANCE(42);
      if (lookahead == 'm') ADVANCE(34);
      if (lookahead == 's') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(29);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == 'g') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'i') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 'i') ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 11:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'p') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(6);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 16:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 18:
      if (eof) ADVANCE(20);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == '|') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 19:
      if (eof) ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_solved_DASHgoto);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_max_DASHinput);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_counting_DASHuntil);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym__number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(29);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == '-') ADVANCE(5);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == '-') ADVANCE(4);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == '-') ADVANCE(17);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == 'a') ADVANCE(47);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == 'd') ADVANCE(32);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == 'e') ADVANCE(35);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == 'g') ADVANCE(33);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == 'i') ADVANCE(41);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == 'l') ADVANCE(46);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == 'n') ADVANCE(44);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == 'n') ADVANCE(37);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == 'o') ADVANCE(45);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == 'o') ADVANCE(39);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == 't') ADVANCE(38);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == 'u') ADVANCE(40);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == 'v') ADVANCE(36);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym__simple_ident);
      if (lookahead == 'x') ADVANCE(31);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym__simple_ident);
      if ((!eof && set_contains(sym__simple_ident_character_set_1, 11, lookahead))) ADVANCE(48);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'P', 1,
        'g', 2,
        'h', 3,
        'i', 4,
        'p', 5,
        'r', 6,
        's', 7,
        'u', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 7:
      if (lookahead == 'o') ADVANCE(15);
      if (lookahead == 'w') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 9:
      if (lookahead == 'z') ADVANCE(18);
      END_STATE();
    case 10:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == 'p') ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 14:
      if (lookahead == 'p') ADVANCE(23);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == 'z') ADVANCE(27);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 21:
      if (lookahead == 'u') ADVANCE(30);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 24:
      if (lookahead == 'v') ADVANCE(33);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 27:
      if (lookahead == 'l') ADVANCE(36);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_goto);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_halt);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 32:
      if (lookahead == 'a') ADVANCE(39);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 34:
      if (lookahead == 'c') ADVANCE(41);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_input);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_print);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(44);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_solve_instruction);
      if (lookahead == 'd') ADVANCE(45);
      END_STATE();
    case 41:
      if (lookahead == 'h') ADVANCE(46);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_until);
      END_STATE();
    case 43:
      if (lookahead == 's') ADVANCE(47);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_repeat);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_solved);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_switch);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_Puzzles);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 19},
  [4] = {.lex_state = 19},
  [5] = {.lex_state = 19},
  [6] = {.lex_state = 19},
  [7] = {.lex_state = 19},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 19},
  [11] = {.lex_state = 19},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 19},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 19},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 18},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 18},
  [26] = {.lex_state = 18},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 19},
  [29] = {.lex_state = 18},
  [30] = {.lex_state = 19},
  [31] = {.lex_state = 19},
  [32] = {.lex_state = 19},
  [33] = {.lex_state = 18},
  [34] = {.lex_state = 18},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 18},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 18},
  [39] = {.lex_state = 18},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 18},
  [42] = {.lex_state = 18},
  [43] = {.lex_state = 18},
  [44] = {.lex_state = 19},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 18},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 18},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 18},
  [57] = {.lex_state = 18},
  [58] = {.lex_state = 18},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__simple_ident] = ACTIONS(1),
    [anon_sym_Puzzles] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_goto] = ACTIONS(1),
    [anon_sym_solved_DASHgoto] = ACTIONS(1),
    [sym_solve_instruction] = ACTIONS(1),
    [anon_sym_repeat] = ACTIONS(1),
    [anon_sym_until] = ACTIONS(1),
    [anon_sym_solved] = ACTIONS(1),
    [anon_sym_input] = ACTIONS(1),
    [anon_sym_max_DASHinput] = ACTIONS(1),
    [anon_sym_halt] = ACTIONS(1),
    [anon_sym_print] = ACTIONS(1),
    [anon_sym_counting_DASHuntil] = ACTIONS(1),
    [anon_sym_switch] = ACTIONS(1),
    [sym__number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(59),
    [sym__puzzle_definition_section] = STATE(26),
    [anon_sym_Puzzles] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(5), 1,
      sym__simple_ident,
    ACTIONS(7), 1,
      anon_sym_goto,
    ACTIONS(9), 1,
      anon_sym_solved_DASHgoto,
    ACTIONS(11), 1,
      sym_solve_instruction,
    ACTIONS(13), 1,
      anon_sym_repeat,
    ACTIONS(15), 1,
      anon_sym_input,
    ACTIONS(17), 1,
      anon_sym_halt,
    ACTIONS(19), 1,
      anon_sym_print,
    ACTIONS(21), 1,
      anon_sym_switch,
    STATE(4), 2,
      sym_move,
      aux_sym_algorithm_repeat1,
    STATE(46), 8,
      sym_goto_instruction,
      sym_solved_goto_instruction,
      sym_repeat_until_instruction,
      sym_input_instruction,
      sym_halt_instruction,
      sym_print_instruction,
      sym_switch_instruction,
      sym_algorithm,
  [42] = 5,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      sym__simple_ident,
    ACTIONS(27), 1,
      sym__number,
    STATE(52), 1,
      sym_algorithm,
    STATE(8), 2,
      sym_move,
      aux_sym_algorithm_repeat1,
  [59] = 4,
    ACTIONS(5), 1,
      sym__simple_ident,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      sym__number,
    STATE(6), 2,
      sym_move,
      aux_sym_algorithm_repeat1,
  [73] = 4,
    ACTIONS(33), 1,
      sym__simple_ident,
    ACTIONS(36), 1,
      sym__number,
    STATE(48), 1,
      sym_puzzle_name,
    STATE(5), 2,
      sym_puzzle_definition,
      aux_sym__puzzle_definition_section_repeat1,
  [87] = 4,
    ACTIONS(38), 1,
      ts_builtin_sym_end,
    ACTIONS(40), 1,
      sym__simple_ident,
    ACTIONS(43), 1,
      sym__number,
    STATE(6), 2,
      sym_move,
      aux_sym_algorithm_repeat1,
  [101] = 4,
    ACTIONS(45), 1,
      sym__simple_ident,
    ACTIONS(47), 1,
      sym__number,
    STATE(48), 1,
      sym_puzzle_name,
    STATE(5), 2,
      sym_puzzle_definition,
      aux_sym__puzzle_definition_section_repeat1,
  [115] = 3,
    ACTIONS(25), 1,
      sym__simple_ident,
    ACTIONS(29), 2,
      anon_sym_max_DASHinput,
      anon_sym_counting_DASHuntil,
    STATE(9), 2,
      sym_move,
      aux_sym_algorithm_repeat1,
  [127] = 3,
    ACTIONS(49), 1,
      sym__simple_ident,
    ACTIONS(38), 2,
      anon_sym_max_DASHinput,
      anon_sym_counting_DASHuntil,
    STATE(9), 2,
      sym_move,
      aux_sym_algorithm_repeat1,
  [139] = 4,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(54), 1,
      sym__simple_ident,
    ACTIONS(56), 1,
      sym__number,
    STATE(11), 2,
      sym_position,
      aux_sym_positions_repeat1,
  [153] = 4,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
    ACTIONS(60), 1,
      sym__simple_ident,
    ACTIONS(63), 1,
      sym__number,
    STATE(11), 2,
      sym_position,
      aux_sym_positions_repeat1,
  [167] = 3,
    ACTIONS(65), 1,
      sym__simple_ident,
    STATE(42), 1,
      sym_algorithm,
    STATE(4), 2,
      sym_move,
      aux_sym_algorithm_repeat1,
  [178] = 3,
    ACTIONS(63), 1,
      anon_sym_solved,
    ACTIONS(67), 1,
      sym__simple_ident,
    STATE(13), 2,
      sym_position,
      aux_sym_positions_repeat1,
  [189] = 3,
    ACTIONS(70), 1,
      sym__simple_ident,
    STATE(58), 1,
      sym_positions,
    STATE(15), 2,
      sym_position,
      aux_sym_positions_repeat1,
  [200] = 3,
    ACTIONS(56), 1,
      sym__number,
    ACTIONS(72), 1,
      sym__simple_ident,
    STATE(20), 2,
      sym_position,
      aux_sym_positions_repeat1,
  [211] = 3,
    ACTIONS(74), 1,
      sym__simple_ident,
    STATE(49), 1,
      sym_positions,
    STATE(24), 2,
      sym_position,
      aux_sym_positions_repeat1,
  [222] = 3,
    ACTIONS(76), 1,
      sym__simple_ident,
    STATE(50), 1,
      sym_algorithm,
    STATE(8), 2,
      sym_move,
      aux_sym_algorithm_repeat1,
  [233] = 3,
    ACTIONS(74), 1,
      sym__simple_ident,
    STATE(51), 1,
      sym_positions,
    STATE(24), 2,
      sym_position,
      aux_sym_positions_repeat1,
  [244] = 3,
    ACTIONS(78), 1,
      sym__simple_ident,
    STATE(48), 1,
      sym_puzzle_name,
    STATE(7), 2,
      sym_puzzle_definition,
      aux_sym__puzzle_definition_section_repeat1,
  [255] = 3,
    ACTIONS(63), 1,
      sym__number,
    ACTIONS(80), 1,
      sym__simple_ident,
    STATE(20), 2,
      sym_position,
      aux_sym_positions_repeat1,
  [266] = 3,
    ACTIONS(65), 1,
      sym__simple_ident,
    STATE(38), 1,
      sym_algorithm,
    STATE(4), 2,
      sym_move,
      aux_sym_algorithm_repeat1,
  [277] = 3,
    ACTIONS(83), 1,
      sym__simple_ident,
    STATE(41), 1,
      sym_positions,
    STATE(10), 2,
      sym_position,
      aux_sym_positions_repeat1,
  [288] = 3,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    ACTIONS(87), 1,
      sym__number,
    STATE(25), 2,
      aux_sym__instructions,
      sym_instruction,
  [299] = 3,
    ACTIONS(56), 1,
      anon_sym_solved,
    ACTIONS(89), 1,
      sym__simple_ident,
    STATE(13), 2,
      sym_position,
      aux_sym_positions_repeat1,
  [310] = 3,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 1,
      sym__number,
    STATE(25), 2,
      aux_sym__instructions,
      sym_instruction,
  [321] = 2,
    ACTIONS(87), 1,
      sym__number,
    STATE(23), 2,
      aux_sym__instructions,
      sym_instruction,
  [329] = 2,
    ACTIONS(96), 1,
      sym__simple_ident,
    ACTIONS(98), 2,
      anon_sym_max_DASHinput,
      anon_sym_counting_DASHuntil,
  [337] = 2,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
    ACTIONS(96), 2,
      sym__number,
      sym__simple_ident,
  [345] = 1,
    ACTIONS(100), 3,
      ts_builtin_sym_end,
      anon_sym_COLON,
      sym__number,
  [351] = 2,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
    ACTIONS(104), 2,
      sym__number,
      sym__simple_ident,
  [359] = 1,
    ACTIONS(106), 2,
      sym__number,
      sym__simple_ident,
  [364] = 1,
    ACTIONS(104), 2,
      sym__number,
      sym__simple_ident,
  [369] = 1,
    ACTIONS(108), 2,
      ts_builtin_sym_end,
      sym__number,
  [374] = 1,
    ACTIONS(110), 2,
      ts_builtin_sym_end,
      sym__number,
  [379] = 2,
    ACTIONS(112), 1,
      anon_sym_until,
    ACTIONS(114), 1,
      sym_string,
  [386] = 1,
    ACTIONS(116), 2,
      ts_builtin_sym_end,
      sym__number,
  [391] = 2,
    ACTIONS(78), 1,
      sym__simple_ident,
    STATE(34), 1,
      sym_puzzle_name,
  [398] = 1,
    ACTIONS(118), 2,
      ts_builtin_sym_end,
      sym__number,
  [403] = 1,
    ACTIONS(120), 2,
      ts_builtin_sym_end,
      sym__number,
  [408] = 1,
    ACTIONS(104), 2,
      anon_sym_solved,
      sym__simple_ident,
  [413] = 1,
    ACTIONS(122), 2,
      ts_builtin_sym_end,
      sym__number,
  [418] = 1,
    ACTIONS(124), 2,
      ts_builtin_sym_end,
      sym__number,
  [423] = 1,
    ACTIONS(126), 2,
      ts_builtin_sym_end,
      sym__number,
  [428] = 1,
    ACTIONS(128), 2,
      sym__number,
      sym__simple_ident,
  [433] = 2,
    ACTIONS(130), 1,
      sym__simple_ident,
    STATE(44), 1,
      sym_puzzle_type,
  [440] = 1,
    ACTIONS(132), 2,
      ts_builtin_sym_end,
      sym__number,
  [445] = 1,
    ACTIONS(134), 1,
      sym_string,
  [449] = 1,
    ACTIONS(136), 1,
      anon_sym_COLON,
  [453] = 1,
    ACTIONS(138), 1,
      anon_sym_solved,
  [457] = 1,
    ACTIONS(140), 1,
      anon_sym_max_DASHinput,
  [461] = 1,
    ACTIONS(142), 1,
      anon_sym_solved,
  [465] = 1,
    ACTIONS(144), 1,
      anon_sym_counting_DASHuntil,
  [469] = 1,
    ACTIONS(146), 1,
      sym_string,
  [473] = 1,
    ACTIONS(148), 1,
      sym__number,
  [477] = 1,
    ACTIONS(150), 1,
      sym_string,
  [481] = 1,
    ACTIONS(152), 1,
      sym__number,
  [485] = 1,
    ACTIONS(154), 1,
      anon_sym_PIPE,
  [489] = 1,
    ACTIONS(156), 1,
      sym__number,
  [493] = 1,
    ACTIONS(158), 1,
      ts_builtin_sym_end,
  [497] = 1,
    ACTIONS(160), 1,
      anon_sym_until,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 42,
  [SMALL_STATE(4)] = 59,
  [SMALL_STATE(5)] = 73,
  [SMALL_STATE(6)] = 87,
  [SMALL_STATE(7)] = 101,
  [SMALL_STATE(8)] = 115,
  [SMALL_STATE(9)] = 127,
  [SMALL_STATE(10)] = 139,
  [SMALL_STATE(11)] = 153,
  [SMALL_STATE(12)] = 167,
  [SMALL_STATE(13)] = 178,
  [SMALL_STATE(14)] = 189,
  [SMALL_STATE(15)] = 200,
  [SMALL_STATE(16)] = 211,
  [SMALL_STATE(17)] = 222,
  [SMALL_STATE(18)] = 233,
  [SMALL_STATE(19)] = 244,
  [SMALL_STATE(20)] = 255,
  [SMALL_STATE(21)] = 266,
  [SMALL_STATE(22)] = 277,
  [SMALL_STATE(23)] = 288,
  [SMALL_STATE(24)] = 299,
  [SMALL_STATE(25)] = 310,
  [SMALL_STATE(26)] = 321,
  [SMALL_STATE(27)] = 329,
  [SMALL_STATE(28)] = 337,
  [SMALL_STATE(29)] = 345,
  [SMALL_STATE(30)] = 351,
  [SMALL_STATE(31)] = 359,
  [SMALL_STATE(32)] = 364,
  [SMALL_STATE(33)] = 369,
  [SMALL_STATE(34)] = 374,
  [SMALL_STATE(35)] = 379,
  [SMALL_STATE(36)] = 386,
  [SMALL_STATE(37)] = 391,
  [SMALL_STATE(38)] = 398,
  [SMALL_STATE(39)] = 403,
  [SMALL_STATE(40)] = 408,
  [SMALL_STATE(41)] = 413,
  [SMALL_STATE(42)] = 418,
  [SMALL_STATE(43)] = 423,
  [SMALL_STATE(44)] = 428,
  [SMALL_STATE(45)] = 433,
  [SMALL_STATE(46)] = 440,
  [SMALL_STATE(47)] = 445,
  [SMALL_STATE(48)] = 449,
  [SMALL_STATE(49)] = 453,
  [SMALL_STATE(50)] = 457,
  [SMALL_STATE(51)] = 461,
  [SMALL_STATE(52)] = 465,
  [SMALL_STATE(53)] = 469,
  [SMALL_STATE(54)] = 473,
  [SMALL_STATE(55)] = 477,
  [SMALL_STATE(56)] = 481,
  [SMALL_STATE(57)] = 485,
  [SMALL_STATE(58)] = 489,
  [SMALL_STATE(59)] = 493,
  [SMALL_STATE(60)] = 497,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print_instruction, 2, 0, 4),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_print_instruction, 2, 0, 4),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_algorithm, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_algorithm, 1, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__puzzle_definition_section_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__puzzle_definition_section_repeat1, 2, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_algorithm_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_algorithm_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_algorithm_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__puzzle_definition_section, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_algorithm_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_positions, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_positions, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_positions_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_positions_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_positions_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_positions_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_positions_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__instructions, 2, 0, 0),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__instructions, 2, 0, 0), SHIFT_REPEAT(57),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_move, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_move, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_puzzle_name, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_position, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_position, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_puzzle_type, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_halt_instruction, 2, 0, 4),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_switch_instruction, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_solved_goto_instruction, 3, 0, 5),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_repeat_until_instruction, 5, 0, 6),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input_instruction, 5, 0, 7),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print_instruction, 5, 0, 8),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_halt_instruction, 6, 0, 9),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_goto_instruction, 2, 0, 3),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_puzzle_definition, 3, 0, 1),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 3, 0, 2),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [158] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_qter_q(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym__simple_ident,
    .primary_state_ids = ts_primary_state_ids,
    .name = "qter_q",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
